// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOm9a-brIT3Xa5MyVK4GrDS8SL4V0n3x8',
    appId: '1:650913341853:web:13fc11159aebea581e0f74',
    messagingSenderId: '650913341853',
    projectId: 'my-pocket-wallet-83de8',
    authDomain: 'my-pocket-wallet-83de8.firebaseapp.com',
    storageBucket: 'my-pocket-wallet-83de8.firebasestorage.app',
    measurementId: 'G-JREB1EF275',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOYAFLsXJs2hk8BUOQ9puL_BQbqzI5lEM',
    appId: '1:650913341853:android:66c59c7acbfb34711e0f74',
    messagingSenderId: '650913341853',
    projectId: 'my-pocket-wallet-83de8',
    storageBucket: 'my-pocket-wallet-83de8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC19wMybkbzERuoiQFarpAPpFQA-Qa_MI',
    appId: '1:650913341853:ios:911e7921b8dfb1791e0f74',
    messagingSenderId: '650913341853',
    projectId: 'my-pocket-wallet-83de8',
    storageBucket: 'my-pocket-wallet-83de8.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC19wMybkbzERuoiQFarpAPpFQA-Qa_MI',
    appId: '1:650913341853:ios:911e7921b8dfb1791e0f74',
    messagingSenderId: '650913341853',
    projectId: 'my-pocket-wallet-83de8',
    storageBucket: 'my-pocket-wallet-83de8.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOm9a-brIT3Xa5MyVK4GrDS8SL4V0n3x8',
    appId: '1:650913341853:web:e6c51d0ae5eff07c1e0f74',
    messagingSenderId: '650913341853',
    projectId: 'my-pocket-wallet-83de8',
    authDomain: 'my-pocket-wallet-83de8.firebaseapp.com',
    storageBucket: 'my-pocket-wallet-83de8.firebasestorage.app',
    measurementId: 'G-4TYMG9JXJP',
  );
}
